name: Cleanup Old Releases

on:
  workflow_dispatch: # Manual trigger
  schedule:
    - cron: '0 2 * * 0' # Weekly on Sunday at 2 AM UTC

permissions:
  contents: write

jobs:
  cleanup:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Delete old releases
        uses: dev-drprasad/delete-older-releases@v0.3.4
        with:
          keep_latest: 5
          delete_tags: false # Keep git tags for history
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

